### ISSUE TITLE
AMA #6

### ISSUE THREAD

**Issue by arbaouimehdi** [freemh/ama#1]
# AMA (Ask Me Anythin) #6

#### Question
> How to build a js developer portfolio? 

#### Answer
- https://github.com/emmabostian/developer-portfolios
- https://dev.to/emmabostian/how-to-build-a-great-technical-portfolio-53bb

#### Question
> thanks khouya mahdi for youtube and fb help job 
bghyt nswlk  i m a java/j2ee dev hadi 2 ans o khddam  l backend b java front end with template engine like thymleaf  ... 
bghyt nbda integrer framwork dial js jatni angulars mkhrb9a ktart.les composants o o bsaf dial file  
i nedd your avis 

#### Answer
- https://dev.to/saschadev/angular-vs-vuejs-vs-react-vs--4lin/comments

#### Question
> bach tnsa7ni n9era bach nwali Full Stack Web Developer (kan3raf l  html & CSS & Bootstrap & chwia Sass) o chnahoma les sites li tnsa7ni n9era fihom (o ana kamlt Responsive Web Design || JavaScript Algorithms and Data Structures) li f freecodecamp

#### Answer

- RoadMap: https://github.com/kamranahmedse/developer-roadmap
- Frontend Projects: https://sketchrepo.com/ and https://codepen.io/popular/collections/ 
- Backend Projects: https://github.com/search?l=JavaScript&q=Project+Management+Tools&type=Repositories

#### Question
> salam 3likom fi lewl bghit nchokrk 3la majhodat litadir w alah ykeml 3lik 
bghit nsewlk 3la 7sb wa7ed exp bghina nkhedmoh bi array w foreach 
function format(numbers) {
    let arr = "(+XXX) XXX-XXXXXX".split('');
     //boucle avec Foreach   d'un tableau de String
  }
> const num = [2,1,2,6,7,1,4,1,5,0,7,5];
> console.log(format(num));
> bghina had arqam li fi num yt2afichaw ina 3la chkel num tél li di blastha XXX

#### Answer
```js
/*!
 * description: Format Phone Numbers
 * Output: (+XXX) XXX-XXXXXX => (+212) 671-415075
 */
function formatPhone(phoneNumber, format) {

  // Replace X by each number on a specific position
	for (let i = 0, l = phoneNumber.length; i < l; i++) {
		format = format.replace(
			"X",
			phoneNumber[i],
		);
	}

	return format;
}

// Test using an array
const num = [2,1,2,6,7,1,4,1,5,0,7,5];
console.log(formatPhone(num, "(+XXX) XXX-XXXXXX"));

// Test using String
const num2 = "212671415075";
console.log(formatPhone(num2, "(+XXX) XXX-XXXXXX"));
```

#### Question
> salam khoya mehdi , ana switchit man js front-end l php back-end 7it m3a lwa9t fhmt bli ana interéssé b back-end  , w hadi chi 1 mois w ana tant3alam basics dial php w mysql (the question is not about php !) , bghit nbda chi mini project walakin fin ma tal9a chi idea , tan la7de bi ana mzl khasnni bzaaaaf bach n9dar n appliquiha , wach back end project dialhom s3ab 3la front end awala hi mal9itch chi idea mzyana , and pls some ideas l begginers f back-end (mzl matan3rafch ndir ta systeme d'authentification),ty !

#### Answer

3endek bzaf dyal l Caregries dyal apps li baghi tssayeb, example: 
- Project Management Tools
- Social Networking
- Help And Support Tools
- Images And Media
- Shopping Carts
- Search
- Calendars
...

Apps Examples:
- https://flaviocopes.com/sample-app-ideas/
- https://github.com/search?l=PHP&q=Project+Management+Tools&type=Repositories
- https://codecanyon.net/category/php-scripts?platform=PHP%207.x&sort=price-asc#content
- https://codecanyon.net/item/phpblog-powerful-blog-cms/5979801
- https://codecanyon.net/item/igniteinvoice-the-invoicing-fast-easy-and-secure-web-invoicing-solution/22257515

Auth System Code & Video Tutorials:
- PHP Auth Systems: https://github.com/search?l=PHP&q=auth+system&type=Repositories
- https://www.youtube.com/watch?v=LC9GaXkdxF8
- https://www.youtube.com/watch?v=DRFdftHS5wc

#### Question
> A very good path to master javascript and angular for an intermediate developer?how much it will take?

JavaScript Expert Topics:
- Functional Programming
- Performance
- Asynchronous
- Webpack 4
- Git
- React or any other JS Framework
- Design Patterns
- Algorithms

#### Question
> Bro any resources or advises to learn ruby and rails

#### Answer
- https://www.railstutorial.org/
- https://github.com/gramantin/awesome-rails

#### Question
> 1- Achnu kat3ni JAM stack , 9elebt f youtube ms mafhemtch mezyan . 2-bach katnse7 beginner fl backend f 2020 php vs node.js ola python ?

#### Answer
- https://jamstack.wtf/
- https://jamstack.org/

#### Question
> how to practice coding from home im only following courses?

#### Answer

- https://flaviocopes.com/sample-app-ideas/

#### Question
> Je fais du developpement web, j'arrive pas à trouver des projets pour pratiquer ReactJS

- https://reactjs.org/community/examples.html
- Airbnb Clone: https://www.youtube.com/watch?v=kuswGIH-Xj8&list=PLN3n1USn4xlnfJIQBa6bBjjiECnk6zL6s

#### Question
> kan créer des project web app ms ba9i ma3ndich fikra 3la kifach n sécuriser les app dyali

#### Answer
- https://github.com/OWASP/wstg/tree/master/document/4_Web_Application_Security_Testing
- https://github.com/OWASP/wstg/blob/master/document/4_Web_Application_Security_Testing/4.1_Introduction_and_Objectives/4.1.1_Testing_Checklist.md

### Youness
> tbark lah 3lik a khay mehdi rak dima top 3andi 2 questions  
1)t9Ad tgolina some good resources to learn php
2)3andii had l3am PFE o bghit n9ad chi web app b stack dyal HTML CSS JS PHP mais bghitek a khay mehdi tgol liya chi idea simple nkhdem 3liha li n9ad nssaliha fi 2 mois hite ana 3amrni 9Adite chi projet hada awel wa7d  o bghite n9Ad chi haja li zwina  tssta7el tkon fi PFE

#### Answer
Learn PHP & Useful Tools:
- https://laracasts.com/
- https://symfonycasts.com/
- https://teamtreehouse.com/library/topic:php
- https://github.com/ziadoz/awesome-php

Project Examples:
- https://codecanyon.net/search/restaurant?utf8=%E2%9C%93
- https://codecanyon.net/search/social%20network?utf8=%E2%9C%93
- https://codecanyon.net/search/car%20rental?utf8=%E2%9C%93
- https://codecanyon.net/search/project%20management?utf8=%E2%9C%93
- https://codecanyon.net/search/hr?utf8=%E2%9C%93

#### Question
> khouya salam , wach ila tb3t dawra dyalk ta3 JavaScript ECMAScript 6, li glti f description dyalha bli 9riba l react js, wach t9dr t3awni fl react native , pcq baghi nt3lm react native okal9a les cours 9lal, ana en general baghi nt3lm developement mobile,  any advice bro?

#### Answer
- https://medium.com/the-react-native-log/a-brief-overview-of-es6-for-react-native-developers-15e7c68315da

**Comment by zak402** [comment]
​salam khoya nswlak ana khdam freelance wla kijini developement tamara dialo ktar man flos et client ki3adbak 9bal ichad lproject kiban lia mkainch most9bal fi freelance man rir ila drti chi saas app

**Comment by Ismailelazzouzi** [comment]
Hello Mehdi I just completed responsive web design certif and I'm making small projects should I start learning javascript ?

**Comment by arbaouimehdi** [comment]
> ​salam khoya nswlak ana khdam freelance wla kijini developement tamara dialo ktar man flos et client ki3adbak 9bal ichad lproject kiban lia mkainch most9bal fi freelance man rir ila drti chi saas app

Hello @zak402 and @Ismailelazzouzi , l question khasshom yt7ato f l google form dyal next AMA, l comment hnaya dyal ila 3endek chi 7aja related l answers li 3tite.

> Dima lien dyal l google form kandirou f l AMA video, as an example ila dkhelti l had lien dyal [AMA #6](https://www.youtube.com/watch?v=ODRJbwNJx3M) ghadi tl9a f description l google form link dyal next AMA #7.

**Comment by hilolo** [comment]
ho can my website manage big quantitys of visitors like (news websites .. ) ?
